kamraapp/apps/bet/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.views.generic import TemplateView, DetailView

from rest_framework import routers

from .views import HomeView, BetListView, BetDetailView, BetCreateView, BetFormView, CloneBetFormView, CounterBetFormView
from .api.views import BetViewset, DonationRecipientViewset

from .models import DonationRecipient


router = routers.SimpleRouter(trailing_slash=False)

router.register(r'bets', BetViewset, base_name='bets')
router.register(r'donation-recipients', DonationRecipientViewset, base_name='donation-recipients')


urlpatterns = patterns('',
    url(r'^$', HomeView.as_view(), name='home'),

    url(r'^contact/$', TemplateView.as_view(template_name='public/contact.html'), name='contact'),
    url(r'^about/$', TemplateView.as_view(template_name='public/about.html'), name='about'),

    url(r'^k/create/$', BetCreateView.as_view(), name='create'),
    url(r'^k/(?P<slug>[\w-]+)/$', BetDetailView.as_view(), name='detail'),
    url(r'^k/(?P<slug>[\w-]+)/edit/$', BetFormView.as_view(), name='edit'),
    url(r'^k/(?P<slug>[\w-]+)/clone/$', CloneBetFormView.as_view(), name='clone'),
    url(r'^k/(?P<slug>[\w-]+)/counter/$', CounterBetFormView.as_view(), name='edit'),

    url(r'^d/(?P<slug>[\w-]+)/$', DetailView.as_view(model=DonationRecipient, template_name='donationrecipient/donationrecipient_detail.html'), name='donationrecipient-detail'),
) + router.urls

kamraapp/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from .static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('kamraapp.apps.bet.urls', namespace='bet')),
    url(r'^featured/', include('kamraapp.apps.featured.urls', namespace='featured')),
]

if settings.DEBUG is True or settings.TEST_PREPROD is True:
    # Add the MEDIA_URL to the dev environment
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load staticfiles pipeline %}<!doctype html>
<html lang="en">
<head>
  <!-- Meta -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>{% block title %}KarmApp - do good, get karma{% endblock %}</title>

  <!-- Favicons -->
  <link rel="icon" type="image/png" href="{% static 'images/favicon.ico' %}">
  <link rel="apple-touch-icon" sizes="57x57" href="{% static 'apple-icon-57x57.png' %}">
  <link rel="apple-touch-icon" sizes="60x60" href="{% static 'apple-icon-60x60.png' %}">
  <link rel="apple-touch-icon" sizes="72x72" href="{% static 'apple-icon-72x72.png' %}">
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'apple-icon-76x76.png' %}">
  <link rel="apple-touch-icon" sizes="114x114" href="{% static 'apple-icon-114x114.png' %}">
  <link rel="apple-touch-icon" sizes="120x120" href="{% static 'apple-icon-120x120.png' %}">
  <link rel="apple-touch-icon" sizes="144x144" href="{% static 'apple-icon-144x144.png' %}">
  <link rel="apple-touch-icon" sizes="152x152" href="{% static 'apple-icon-152x152.png' %}">
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-icon-180x180.png' %}">
  <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'android-icon-192x192.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="96x96" href="{% static 'favicon-96x96.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.png' %}">
  <link rel="manifest" href="{% static 'manifest.json' %}">
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="{% static 'ms-icon-144x144.png' %}">
  <meta name="theme-color" content="#ffffff">

  <!-- Fonts -->
  <link href="http://fonts.googleapis.com/css?family=Lato:400,900,300,700" rel="stylesheet">
  <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700,400italic,700italic" rel="stylesheet">

  {% block head %}{% endblock %}

  <!-- inject:css -->
  {% block compressedcss %}
    {% stylesheet 'common' %}
  {% endblock %}
  <!-- endinject -->

  <!-- HTML5 elements and media queries Support for IE8 : HTML5 shim and Respond.js -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->

  {% block css_header %}{% endblock %}
  {% block javascript_header %}{% endblock %}
</head>

<body>

  <header>
    <div class="navbar">
      <div class="navbar-header">
        <div class="container">

          <ul class="info pull-left">
            <li><a href="#"><i class="icon-mail-1 contact"></i>info[at]karma-app.io</a></li>
            <!-- <li><i class="icon-mobile contact"></i> +00 (123) 456 78 90</li> -->
          </ul><!-- /.info -->

          <ul class="social pull-right">
            <li><a href="#"><i class="icon-s-facebook"></i></a></li>
            <li><a href="#"><i class="icon-s-gplus"></i></a></li>
            <li><a href="#"><i class="icon-s-twitter"></i></a></li>
            <li><a href="#"><i class="icon-s-pinterest"></i></a></li>
            <li><a href="#"><i class="icon-s-behance"></i></a></li>
            <li><a href="#"><i class="icon-s-dribbble"></i></a></li>
          </ul><!-- /.social -->

          <!-- ============================================================= LOGO MOBILE ============================================================= -->

          <a class="navbar-brand" href="{% url 'bet:home' %}">
            <img src="{% static 'images/karma.png' %}" class="logo" alt="">
          </a>

          <!-- ============================================================= LOGO MOBILE : END ============================================================= -->

          <a class="btn responsive-menu pull-right" data-toggle="collapse" data-target=".navbar-collapse"><i class='icon-menu-1'></i></a>

        </div><!-- /.container -->
      </div><!-- /.navbar-header -->

      <div class="yamm">
        <div class="navbar-collapse collapse">
          <div class="container">

            <!-- ============================================================= LOGO ============================================================= -->

            <a class="navbar-brand" href="{% url 'bet:home' %}">
              <img src="{% static 'images/karma.png' %}" class="logo" alt="">
            </a>

            <!-- ============================================================= LOGO : END ============================================================= -->


            <!-- ============================================================= MAIN NAVIGATION ============================================================= -->


            <ul class="nav navbar-nav">
              <li><a href="{% url 'bet:create' %}">Generate Karma</a></li>
              <li><a href="{% url 'bet:about' %}">About</a></li>
              <li><a href="{% url 'bet:contact' %}">Contact</a></li>

              {% if user.is_authenticated %}
                <li class="">
                  <a href="#" class="dropdown-toggle js-activated">{{ user.get_full_name|default:user.email }}</a>
                </li>
                <li><a href="#">Profil</a></li>
                <li><a href="#">Logout</a></li>
              {% else %}
                <li class="pull-right"><a href=>Sign in</a></li>
              {% endif %}

              <li class="dropdown pull-right searchbox">
                <a href="#" class="dropdown-toggle js-activated"><i class="icon-search"></i></a>
                <div class="dropdown-menu">
                  <form id="search" class="navbar-form search" role="search">
                    <input type="search" class="form-control" placeholder="Type to search">
                    <button type="submit" class="btn btn-default btn-submit icon-right-open"></button>
                  </form>
                </div><!-- /.dropdown-menu -->
              </li><!-- /.searchbox -->
            </ul><!-- /.nav -->

            <!-- ============================================================= MAIN NAVIGATION : END ============================================================= -->

          </div><!-- /.container -->
        </div><!-- /.navbar-collapse -->
      </div><!-- /.yamm -->
    </div><!-- /.navbar -->
  </header>


  <main>
    {% block content %}{% endblock %}
  </main>

    <!-- ============================================================= MAIN : END ============================================================= -->


    <!-- ============================================================= FOOTER ============================================================= -->

    <footer class="dark-bg">
      <div class="container inner">
        <div class="row">

          <div class="col-md-3 col-sm-6 inner">
            <h4>Who we are</h4>
            <a href="index.html"><img class="logo img-intext" src="{% static 'images/logo-white.svg' %}" alt=""></a>
            <p>Magnis modipsae voloratati andigen daepeditem quiate re porem que aut labor. Laceaque eictemperum quiae sitiorem rest non restibusaes maio es dem tumquam.</p>
            <a href="about.html" class="txt-btn">More about us</a>
          </div><!-- /.col -->

          <div class="col-md-3 col-sm-6 inner">
            <h4>Latest works</h4>

            <div class="row thumbs gap-xs">

              <div class="col-xs-6 thumb">
                <figure class="icon-overlay icn-link">
                  <a href="portfolio-post.html"><img src="{% static 'images/art/work02.jpg' %}" alt=""></a>
                </figure>
              </div><!-- /.thumb -->

              <div class="col-xs-6 thumb">
                <figure class="icon-overlay icn-link">
                  <a href="portfolio-post.html"><img src="{% static 'images/art/work03.jpg' %}" alt=""></a>
                </figure>
              </div><!-- /.thumb -->

              <div class="col-xs-6 thumb">
                <figure class="icon-overlay icn-link">
                  <a href="portfolio-post.html"><img src="{% static 'images/art/work07.jpg' %}" alt=""></a>
                </figure>
              </div><!-- /.thumb -->

              <div class="col-xs-6 thumb">
                <figure class="icon-overlay icn-link">
                  <a href="portfolio-post.html"><img src="{% static 'images/art/work01.jpg' %}" alt=""></a>
                </figure>
              </div><!-- /.thumb -->

            </div><!-- /.row -->
          </div><!-- /.col -->


          <div class="col-md-3 col-sm-6 inner">
            <h4>Get In Touch</h4>
            <p>Doloreiur quia commolu ptatemp dolupta oreprerum tibusam eumenis et consent accullignis dentibea autem inisita.</p>
            <ul class="contacts">
              <li><i class="icon-location contact"></i> 84 Street, City, State 24813</li>
              <li><i class="icon-mobile contact"></i> +00 (123) 456 78 90</li>
              <li><a href="#"><i class="icon-mail-1 contact"></i> info@reen.com</a></li>
            </ul><!-- /.contacts -->
          </div><!-- /.col -->

          <div class="col-md-3 col-sm-6 inner">
            <h4>Free updates</h4>
            <p>Conecus iure posae volor remped modis aut lor volor accabora incim resto explabo.</p>
            <form id="newsletter" class="form-inline newsletter" role="form">
              <label class="sr-only" for="exampleInputEmail">Email address</label>
              <input type="email" class="form-control" id="exampleInputEmail" placeholder="Enter your email address">
              <button type="submit" class="btn btn-default btn-submit">Subscribe</button>
            </form>
          </div><!-- /.col -->

        </div><!-- /.row -->
      </div><!-- .container -->

      <div class="footer-bottom">
        <div class="container inner">
          <p class="pull-left">© 2014 REEN. All rights reserved.</p>
          <ul class="footer-menu pull-right">
            <li><a href="index.html">Home</a></li>
            <li><a href="portfolio.html">Portfolio</a></li>
            <li><a href="blog.html">Blog</a></li>
            <li><a href="about.html">About</a></li>
            <li><a href="services.html">Services</a></li>
            <li><a href="contact.html">Contact</a></li>
          </ul><!-- .footer-menu -->
        </div><!-- .container -->
      </div><!-- .footer-bottom -->
    </footer>

    <!-- ============================================================= FOOTER : END ============================================================= -->

  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/js/bootstrap.min.js"></script>

  {% javascript 'common' %}
  {% javascript 'angular' %}
  {% block javascript_footer %}{% endblock %}
  {% block compressedjs %}{% endblock %}

</body>
</html>