kamraapp/apps/bet/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.views.generic import TemplateView, DetailView

from rest_framework import routers

from .views import HomeView, BetListView, BetDetailView, BetCreateView, BetFormView, CloneBetFormView, CounterBetFormView
from .api.views import BetViewset, DonationRecipientViewset

from .models import DonationRecipient


router = routers.SimpleRouter(trailing_slash=False)

router.register(r'bets', BetViewset, base_name='bets')
router.register(r'donation-recipients', DonationRecipientViewset, base_name='donation-recipients')


urlpatterns = patterns('',
    url(r'^$', HomeView.as_view(), name='home'),

    url(r'^contact/$', TemplateView.as_view(template_name='public/contact.html'), name='contact'),
    url(r'^about/$', TemplateView.as_view(template_name='public/about.html'), name='about'),

    url(r'^k/create/$', BetCreateView.as_view(), name='create'),
    url(r'^k/(?P<slug>[\w-]+)/$', BetDetailView.as_view(), name='detail'),
    url(r'^k/(?P<slug>[\w-]+)/edit/$', BetFormView.as_view(), name='edit'),
    url(r'^k/(?P<slug>[\w-]+)/clone/$', CloneBetFormView.as_view(), name='clone'),
    url(r'^k/(?P<slug>[\w-]+)/counter/$', CounterBetFormView.as_view(), name='edit'),

    url(r'^d/(?P<slug>[\w-]+)/$', DetailView.as_view(model=DonationRecipient, template_name='donationrecipient/donationrecipient_detail.html'), name='donationrecipient-detail'),
) + router.urls

kamraapp/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from .static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('kamraapp.apps.bet.urls', namespace='bet')),
    url(r'^featured/', include('kamraapp.apps.featured.urls', namespace='featured')),
]

if settings.DEBUG is True or settings.TEST_PREPROD is True:
    # Add the MEDIA_URL to the dev environment
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

kamraapp/apps/bet/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.template.defaultfilters import slugify

#from crispy_forms.helper import FormHelper

from .models import Bet, DonationRecipient

import uuid


def _user_exists(username):
    try:
        return User.objects.get(username=username)
    except User.DoesNotExist:
        return None


def _get_unique_username(username):
    username = slugify(username)  # apply the transforms first so that the lookup acts on the actual username
    username = username[0:29]
    while _user_exists(username=username):
        username = '%s-%s' % (username, uuid.uuid4().get_hex()[:4])
        username = username[0:29]  # be aware of fencepost error here field limit is 30

    return username


class BetFormStart(forms.Form):
    name = forms.CharField(label='Your Karma Generating bet', help_text='A short decription of what you will do.')
    description = forms.CharField(label='Details:', help_text='Describe the details of the commitment', widget=forms.Textarea)
    amount = forms.FloatField(label='Donation:', initial=5.00, help_text='Proportionate to the karma generated.')
    donation_recipient = forms.IntegerField(required=False, widget=forms.HiddenInput)

    class Media:
        css = {
            'all': ('//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css',)
        }
        js = {
            'js/project-list-app.js',
            '//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.min.js',
        }

    # class Meta:
    #     model = Bet
    #     exclude = ('slug', 'uuid', 'parent_bet_id', 'created_at', 'updated_at')

    # @property
    # def helper(self):
    #     helper = FormHelper()
    #     helper.form_id = 'support-form'
    #     helper.form_class = 'form'
    #     helper.form_method = 'POST'
    #     return helper
    def save(self, *args, **kwargs):
        obj = Bet(
            name=self.cleaned_data['name'],
            description=self.cleaned_data['description'],
            amount=self.cleaned_data['amount'],
        )
        obj.save()
        is_new = True
        return (obj, is_new)


class BetFormDonationRecipient(forms.ModelForm):
    class Meta:
        model = DonationRecipient
        fields = ('name', 'url', 'description')


class BetFormUserInfo(forms.Form):
    name = forms.CharField(label='Your Name')
    email = forms.EmailField()
    password = forms.CharField(label='A password', widget=forms.PasswordInput)

    def save(self, *args, **kwargs):
        username = self.cleaned_data['email'].split('@')[0]
        obj, is_new = User.objects.get_or_create(username=_get_unique_username(username),
                                                 email=self.cleaned_data['email'])
        if is_new is True:
            name = self.cleaned_data['name'].split(' ')
            obj.first_name = name[0]
            obj.last_name = ' '.join(name[1:])
            obj.set_password(self.cleaned_data['password'])
            obj.save(update_fields=['first_name', 'last_name', 'password'])

        return (obj, is_new)


class ShareForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea)


class CanModifyForm(forms.Form):
    password = forms.CharField()

    def __init__(self, bet, *args, **kwargs):
        self.bet = bet
        super(CanModifyForm, self).__init__(*args, **kwargs)

    def validate_password(self, value):
        if self.bet.slug != value:
            forms.ValidationError('Incorrect Password Please try again')
        return value

kamraapp/apps/bet/api/views.py
# -*- coding: utf-8 -*-
from django.db import models

from rest_framework import viewsets
from rest_framework.response import Response
from rest_framework import status as http_status
from rest_framework.decorators import detail_route
#from rest_framework_extensions.mixins import CacheResponseAndETAGMixin

from ..models import Bet, DonationRecipient
from .serializers import BetSerializer, DonationRecipientSerializer


class BetViewset(viewsets.ReadOnlyModelViewSet):
    """
    """
    model = Bet
    serializer_class = BetSerializer
    queryset = Bet.objects.all()

    @detail_route(methods=['GET', 'POST'])
    def bets_for(self, request, *args, **kwargs):
        self.object = self.get_object()
        if request.method == 'GET':
            data = self.object.data.get('bets_for', self.object.updated_bets_data(bet_type=self.object.SUB_BET_TYPE.bet_for))
        else:
            # do posty stuff
            new_bet = self.get_object()
            new_bet.pk = None
            new_bet.slug = None
            new_bet.user = request.user
            new_bet.parent_bet = self.object
            new_bet.sub_bet_type = new_bet.SUB_BET_TYPE.bet_for
            new_bet.data = {}
            new_bet.save()
            # update the original bet data
            self.object.data['bets_for'] = data = self.object.updated_bets_data(bet_type=self.object.SUB_BET_TYPE.bet_for)
            self.object.save(update_fields=['data'])

        return Response(data, status=http_status.HTTP_200_OK)

    @detail_route(methods=['GET', 'POST'])
    def bets_against(self, request, *args, **kwargs):
        self.object = self.get_object()
        if request.method == 'GET':
            data = self.object.data.get('bets_against', self.object.updated_bets_data(bet_type=self.object.SUB_BET_TYPE.bet_against))
        else:
            # do posty stuff
            new_bet = self.get_object()
            new_bet.pk = None
            new_bet.slug = None
            new_bet.user = request.user
            new_bet.parent_bet = self.object
            new_bet.sub_bet_type = new_bet.SUB_BET_TYPE.bet_against
            new_bet.data = {}
            new_bet.save()
            self.object.data['bets_against'] = data = self.object.updated_bets_data(bet_type=self.object.SUB_BET_TYPE.bet_against)
            # update the data
            self.object.save(update_fields=['data'])

        return Response(data, status=http_status.HTTP_200_OK)


class DonationRecipientViewset(viewsets.ReadOnlyModelViewSet):
    """
    """
    model = DonationRecipient
    serializer_class = DonationRecipientSerializer
    queryset = DonationRecipient.objects.all()

kamraapp/apps/bet/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import redirect
from django.core.urlresolvers import reverse
from django.shortcuts import render_to_response
from django.contrib.auth import authenticate, login
from django.views.generic import UpdateView, ListView, DetailView

from formtools.wizard.views import SessionWizardView

from .models import Bet, DonationRecipient
from .forms import BetFormStart, BetFormDonationRecipient, BetFormUserInfo, ShareForm
from .api.serializers import DonationRecipientSerializer, BetSerializer


class BetListView(ListView):
    """
    """
    model = Bet


def show_donation_recipient_form(wizard):
    """Return true if user opts to pay by credit card"""
    # Get cleaned data from payment step
    cleaned_data = wizard.get_cleaned_data_for_step('0') or {'donation_recipient': None}
    return cleaned_data.get('donation_recipient') is None


def show_user_info_form(wizard):
    """
    """
    return wizard.request.user.is_authenticated() is False


class BetCreateView(SessionWizardView):
    """
    """
    TEMPLATES = {
        '0': 'bet/bet_form_with_donation_recipients.html'
    }

    condition_dict = {
        '1': show_donation_recipient_form,
        '2': show_user_info_form,
    }
    form_list = [BetFormStart, BetFormDonationRecipient, BetFormUserInfo]

    # form_dict = {'bet': BetFormStart,
    #              'recipient': BetFormDonationRecipient,
    #              'user': BetFormUserInfo,}

    template_name = 'bet/bet_form.html'

    def get_template_names(self):
        try:
            return [self.TEMPLATES[self.steps.current]]
        except:
            return self.template_name

    def get_success_url(self):
        return reverse('bet:detail', kwargs={'slug': self.bet.slug})

    def done(self, form_list, form_dict, **kwargs):
        self.bet, is_new = form_dict['0'].save()

        if '1' in form_dict.keys() and form_dict['1'].is_valid():
            donation_recipient = form_dict['1'].save()
        else:
            donation_recipient = DonationRecipient.objects.get(pk=form_dict['0'].cleaned_data.get('donation_recipient'))

        if '2' in form_dict.keys() and form_dict['2'].is_valid():
            user, is_new = form_dict['2'].save()
            # Log the user in
            user = authenticate(username=user.username,
                                password=form_dict['2'].cleaned_data.get('password'))
            login(self.request, user)
        else:
            user = self.request.user

        # save the user associated with this bet
        self.bet.user = user
        self.bet.save(update_fields=['user'])
        self.bet.recipients.add(donation_recipient)

        return redirect(self.get_success_url())


class CloneBetFormView(BetCreateView):
    """
    Same functioanlity as create
    """

    def get_form_initial(self, step):
        self.bet_to_clone = Bet.objects.get(slug=self.kwargs.get('slug'))
        initial = super(CloneBetFormView, self).get_form_initial(step=step)
        if step == '0':
            initial.update({
                'name': self.bet_to_clone.name,
                'description': self.bet_to_clone.description,
                'amount': self.bet_to_clone.amount,
                'donation_recipient': self.bet_to_clone.recipients.all().first().pk,
            })

        return initial

    def done(self, *args, **kwargs):
        redirect = super(CloneBetFormView, self).done(*args, **kwargs)

        # Setup the clone variables
        self.bet.parent_bet = self.bet_to_clone
        self.bet.sub_bet_type = Bet.SUB_BET_TYPE.clone
        self.bet.save(update_fields=['parent_bet', 'sub_bet_type'])
        # redirect
        return redirect


class BetDetailView(DetailView):
    """
    """
    model = Bet

    def user_has_cloned_bet(self):
        return self.object.bet_set.filter(user=self.request.user).count() == 1

    def get_context_data(self, *args, **kwargs):
        context = super(BetDetailView, self).get_context_data(*args, **kwargs)
        url = self.request.build_absolute_uri()
        context.update({
            'facebook_share_form': ShareForm(initial={'text': 'facebook share content here: %s' % url}),
            'twitter_share_form': ShareForm(initial={'text': 'twitter share content here: %s' % url}),
            'donation_recipients': DonationRecipientSerializer(self.object.recipients.all(), many=True).data
        })
        return context


class BetFormView(UpdateView):
    """
    """
    model = Bet
    form_class = BetFormStart
    template_name = 'bet/bet_form.html'


class CounterBetFormView(BetFormView):
    def get_initial(self):
        initial = super(CounterBetFormView, self).get_initial()
        initial.update({'parent_bet': self.get_object()})
        return initial


class HomeView(ListView):
    model = Bet
    paginate_by = 5
    template_name = "public/home.html"

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context.update({
            'bet_list': BetSerializer(context.get('bet_list', []), many=True).data,
            'recipient_list': DonationRecipientSerializer(DonationRecipient.objects.all()[:18], many=True).data
        })
        return context

kamraapp/apps/bet/templates/bet/base.html
{% extends 'base.html' %}

kamraapp/apps/bet/templates/bet/bet_detail.html
{% extends 'bet/base.html' %}{% load social_sharing pipeline %}

{% block title %}{{ bet.user.first_name }} commits to {{ bet.name }} - KarmApp{% endblock %}

{% block head %}
  <!-- SocialSharing -->
  <meta name="description" content="{{ bet.user.first_name }} commits to {{ bet.name }}">
  <meta name="keywords" content="">
  <meta property="og:title" content="{{ bet.user.first_name }} commits to {{ bet.name }}" />
  <meta property="og:description" content="{{ bet.description }}" />
  <meta property="og:image" content="" />
{% endblock %}

{% block content %}
<div class="container inner" ng-app="ProjectDetailApp">
  <div class="row">

    <div class="col-md-12">


      <div class="row text-left">
        {% social_share url=request.build_absolute_uri|escape %}
      </div>

      <hr/>

      {% if user == object.user %}
      <div class="row">
        <a href="{% url 'bet:edit' slug=bet.slug %}" class="btn btn-primary pull-right">edit</a>
      </div>
      {% endif %}

      <div class="row">
        <div class="col-md-6">
          {% if object.parent_bet %}
          <p>Clone of <a href="{{ object.parent_bet.get_absolute_url }}">{{ object.parent_bet.name }} by {{ object.parent_bet.user.first_name }}</a></p>
          {% endif %}
          I, known as "{{ bet.user.first_name }}" swear I will try to "{{ bet.name }}"
          <p>{{ bet.description }}</p>
          {% if user != object.user and not view.user_has_cloned_bet %}
          <a href="{% url 'bet:clone' slug=object.slug %}" class="btn btn-warning">I also want to do this bet</a>
          {% endif %}
        </div>

        <div class="col-md-6">
          <h2>Donation Recipient</h2>
          {% for recipient in donation_recipients %}
          <div class="media">
            <div class="media-top">
              <a href="#"><img class="media-object img-rounded" src="{{ recipient.picture }}" alt="{{ recipient.name }}" /></a>
            </div>
            <div class="media-body">
                <b class="media-heading">{{ recipient.name }}</b>
                <div>{{ recipient.description|safe }}</div>
                <a href="{{ recipient.url }}" target="_NEW" class="btn btn-sm btn-warning">More Info</a>
                <a href="{{ recipient.url }}" target="_NEW" class="btn btn-sm btn-success">Donate now</a>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>

      <hr/>

      <div class="row">

        <div class="col-md-4">
          <ul class="">
          <li><b>Primary:</b> {{ bet.amount }}</li>
          <li><b>For:</b></li>
          <li><b>Against:</b></li>
          <li><b>Donation Total:</b></li>
          <li><b>Karma Total:</b></li>
          <ul>
        </div>

        <div class="col-md-4">
          {% if user != object.user %}
          {% verbatim %}
          <span ng-controller="BetForController">
          <a href="" ng-show="can_bet " ng-click="bet_for()" class="btn btn-success">Bet for</a><br/>
          {{ bets.total }}
          <ul>
            <li ng-repeat="bet in data.bets track by $index">
              {{ bet.name }}
            </li>
          </ul>
          </span>
          {% endverbatim %}
          {% endif %}
        </div>
        <div class="col-md-4">
          {% if user != object.user %}
          {% verbatim %}
          <span ng-controller="BetAgainstController">
          <a href="" ng-show="can_bet " ng-click="bet_against()" class="btn btn-danger">Bet Against</a><br/>
          {{ bets.total }}
          <ul>
            <li ng-repeat="bet in data.bets track by $index">
              {{ bet.name }}
            </li>
          </ul>
          </span>
          {% endverbatim %}
          {% endif %}
        </div>

      </div>
      {% if bet.bet_set.all %}
      <div class="row">
        <h3>Others doing this bet</h3>
        <ol>
        {% for other_bet in bet.bet_set.all %}
        <li><a href="{{ other_bet.get_absolute_url }}">{{ other_bet.name }}</a></li>
        {% endfor %}
        </ol>
      </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

{% block javascript_footer %}
{% javascript 'project-detail' %}
<script>
window.bet = {
  "pk": {{ bet.pk }}
};
window.user = {
  "pk": {{ user.pk|default:'"null"' }}
};
</script>
{% endblock %}

kamraapp/apps/bet/templates/bet/bet_form.html
{% extends 'bet/base.html' %}{% load staticfiles %}

{% block css_header %}{% endblock %}

{% block content %}
  <p>Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</p>
  <form name="" id="" action="{{ form.action }}" method="POST">{% csrf_token %}
    {{ wizard.management_form }}
    {{ wizard.form.as_p }}
  <button type="submit" name="">Submit</button>
  </form>
{% endblock %}

{% block javascript_footer %}
{{ form.media }}
{% endblock %}

kamraapp/apps/bet/templates/bet/bet_form_with_donation_recipients.html
{% extends 'bet/base.html' %}{% load featured_html %}{% load staticfiles pipeline %}

{% block css_header %}
  {% stylesheet 'common' %}
{% endblock %}

{% block content %}
  <div ng-app="ProjectListApp">
    <div class="container inner">
      <div class="row">
        <div class="col-md-8 inner-right-md">

          <section id="hero">
          <header>
            <h1>Generate Karma</h1>
            <small>Select one of our Worthy Causes, or create your own</small>
          </header>
          </section>

          <!-- ============================================================= SECTION – CONTACT FORM ============================================================= -->
          <section id="contact-form" ng-controller="SelectedProjectController">
            <h2>Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</h2>

            {% verbatim %}
            <div class="row well">
              <div class="row" ng-cloak>
                  <div class="col-md-6">
                    <b class="media-heading">{{ project.name || 'Create a new worthy Cause' }}</b>
                    <a href="javascript:false;" ng-show="project" ng-click="clearSelectedProject()" class="btn btn-warning">Change</a>
                  </div>
                  <div class="col-md-3 text-right">
                    <img width="350" height"175" class="media-object img-rounded" src="{{ project.picture || 'https://placeholdit.imgix.net/~text?txtsize=33&txt=New%20Worthy%20Cause&w=350&h=175' }}" alt="{{ project.name }}" />
                  </div>
              </div>
            </div>
            <div class="karma-counter"></div>
            {% endverbatim %}

            <form name="" id="" action="{{ form.action }}" method="POST">{% csrf_token %}
              {{ wizard.management_form }}
              {{ wizard.form.as_p }}
              <button class="btn btn-default btn-submit" type="submit" name="">Continue</button>
            </form>

          </section>
          <!-- ============================================================= SECTION – CONTACT FORM : END ============================================================= -->


        </div><!-- ./col -->
        <div class="col-md-4" ng-controller="ProjectListController">
          <!-- ============================================================= SECTION – CONTACT NAMES ============================================================= -->
          {% verbatim %}
            <section ng-cloak id="contact-names" class="light-bg inner-xs inner-left-xs inner-right-xs">
              <h3 class="team-headline sidelines text-center"><span>Top Projects</span></h3>

              <div class="text-center row">
                <a class="btn btn-default" ng-show="previous_page" href="javascript:false;" ng-click="go(previous_page)">Previous</a>
                <a class="btn btn-default" ng-show="next_page" href="javascript:false;" ng-click="go(next_page)">Next</a>
              </div>


              <div class="row thumbs gap-md text-center" ng-show="projects" ng-repeat="project in projects track by $index">
              <div class="loading" ng-show="projects.length==0">Please wait...</div>
                <div class="col-sm-12 thumb" ng-style="{'cursor':'pointer', 'opacity': 100}" ng-click="selectProject(project)">
                  <figure class="member">
                    <div class="member-image">
                      <div class="text-overlay">
                        <div class="info">
                          <h3>Select this Cause</h3>
                        </div><!-- /.info -->
                      </div><!-- /.text-overlay -->

                      <a href="{{ project.url }}">
                        <img ng-src="{{ project.picture }}" alt="{{ project.name }}">
                      </a>

                    </div><!-- /.member-image -->

                    <figcaption class="member-details bordered no-top-border">
                      <h3>
                        {{ project.name }}
                        <span>{{ project.short_description }}</span>
                      </h3>
                    </figcaption>

                  </figure>
                </div><!-- /.col -->
              </div><!-- /.row -->
            </section>
          {% endverbatim %}
          <!-- ============================================================= SECTION – CONTACT NAMES : END ============================================================= -->

        </div><!-- /.col -->

      </div><!-- /.row -->
    </div><!-- /.container -->
  </div>


{% endblock %}

{% block javascript_footer %}
  {% javascript 'project-list' %}
{% endblock %}

kamraapp/apps/bet/templates/bet/bet_list.html
{% extends 'bet/base.html' %}{% load featured_html %}{% load staticfiles pipeline %}



{% block content %}
  <div ng-app="ProjectListApp">
    <!-- ============================================================= SECTION – HERO ============================================================= -->
    <section id="hero" class="dark-bg">
      <div class="container">
        <div class="row inner">
          <div class="col-sm-10 center-block text-center">
            <header>
              <h1>Featured Donation Beneficiaries</h1>
              <p>Magnis modipsae voloratati andigen daepeditem quiate re porem. Laceaque aut labor eictemperum quiae sitiorem rest non restibusaes maio es dem tumquam.</p>
            </header>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container -->
    </section>
    <!-- ============================================================= SECTION – HERO : END ============================================================= -->

    <!-- ============================================================= SECTION – SELECTED WORKS ============================================================= -->
    <section id="selected-works" class="dark-bg">
      <div class="portfolio">

        <div class="container inner-bottom-xs">
          <ul class="filter text-center">
            <li><a href="#" data-filter="*" class="active">All</a></li>
            <li><a href="#" data-filter=".refugees">Refugees</a></li>
            <li><a href="#" data-filter=".children">Children</a></li>
            <li><a href="#" data-filter=".animals">Animals</a></li>
            <li><a href="#" data-filter=".disease">Disease</a></li>
          </ul><!-- /.filter -->
        </div>

        <ul class="items fullscreen" ng-controller="ProjectListController">

          {% verbatim %}
            <li class="item thumb refugees" ng-show="projects" ng-repeat="project in projects track by $index">
              <a href="{{ project.url }}">
                <figure>
                  <figcaption class="text-overlay">
                    <div class="info">
                      <h4>{{ project.name }}</h4>
                      <p>{{ project.tag || "We need a tag or something..." }}</p>
                    </div><!-- /.info -->
                  </figcaption>
                  <img ng-hide="{{project.picture == ''}}" ng-src="{{ project.picture }}" alt="{{ project.name }}">
                  <img ng-hide="{{project.picture != ''}}" src="http://placehold.it/350x150" alt="{{ project.name }}">
                </figure>
              </a>
            </li><!-- /.item -->
          {% endverbatim %}

        </ul><!-- /.items -->

      </div><!-- /.portfolio -->
    </section>
    <!-- ============================================================= SECTION – SELECTED WORKS : END ============================================================= -->

    <!-- ============================================================= SECTION – REASONS ============================================================= -->
    <section id="reasons">
      <div class="container inner">
        <div class="row">
          <div class="col-md-8 col-sm-9 center-block text-center">
            <header>
              <h1>5 last bets and donations, get inspired!</h1>
            </header>
          </div><!-- /.col -->
        </div><!-- /.row -->

        <div class="row inner-top-sm">
          <div class="col-xs-12">
            {% if object_list %}
              <div class="tabs tabs-reasons tabs-circle-top tab-container">
                <ul class="etabs text-center">
                  {% for i, bet in object_list %}
                    <li class="tab"><a href="#{{ bet.slug }}"><div>{{ i|add:"1" }}</div>{{ bet.name }}</a></li>
                  {% endfor %}
                </ul><!-- /.etabs -->

                <div class="panel-container">
                  {% for bet in object_list %}
                    <div class="tab-content" id="{{ bet.slug }}">
                      <div class="row">
                        <div class="col-md-5 col-md-push-5 col-md-offset-1 col-sm-6 col-sm-push-6 inner-left-xs">
                          <figure><img src="http://placehold.it/300x250" alt=""></figure>
                        </div><!-- /.col -->

                        <div class="col-md-5 col-md-pull-5 col-sm-6 col-sm-pull-6 inner-top-xs inner-right-xs">
                          <h3>Function</h3>
                          <p>Magnis modipsae que lib voloratati andigen daepedor quiate ut reporemni aut labor. Laceaque quiae sitiorem ut restibusaes es tumquam core posae volor remped modis volor. Doloreiur qui commolu ptatemp dolupta orem retibusam emnis et consent accullignis lomnus.</p>
                        </div><!-- /.col -->

                      </div><!-- /.row -->
                    </div><!-- /.tab-content -->
                  {% endfor %}
                </div><!-- /.panel-container -->
              </div><!-- /.tabs -->
            {% endif %}
          </div><!-- /.col -->
        </div><!-- /.row -->

      </div><!-- /.container -->
    </section>
    <!-- ============================================================= SECTION – REASONS : END ============================================================= -->

    <!-- ============================================================= SECTION – GET IN TOUCH ============================================================= -->
    <section id="get-in-touch" class="inner-bottom">
      <div class="container inner light-bg">
        <div class="row">
          <div class="col-md-8 col-sm-9 center-block text-center">
            <header>
              <h1>Want to earn some karma points?</h1>
              <p>You can challenge yourself and your friends and donate the betting proceeds.</p>
            </header>
            <a href="{% url 'bet:create' %}" class="btn btn-large">Get in touch</a>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container -->
    </section>
    <!-- ============================================================= SECTION – GET IN TOUCH : END ============================================================= -->

    <!-- ============================================================= SECTION – SHARE ============================================================= -->
    <section id="share" class="light-bg">
      <div class="row">

        <div class="col-sm-4 reset-padding-right">
          <a href="#" class="btn-share-md">
            <p class="name">Facebook</p>
            <i class="icon-s-facebook"></i>
            <p class="counter">1080</p>
          </a>
        </div><!-- /.col -->

        <div class="col-sm-4 reset-padding">
          <a href="#" class="btn-share-md">
            <p class="name">Twitter</p>
            <i class="icon-s-twitter"></i>
            <p class="counter">1263</p>
          </a>
        </div><!-- /.col -->

        <div class="col-sm-4 reset-padding-left">
          <a href="#" class="btn-share-md">
            <p class="name">Google +</p>
            <i class="icon-s-gplus"></i>
            <p class="counter">963</p>
          </a>
        </div><!-- /.col -->

      </div><!-- /.row -->
    </section>
    <!-- ============================================================= SECTION – SHARE : END ============================================================= -->
  </div>

{% endblock %}


{% javascript 'common' %}
{% javascript 'angular' %}
{% block javascript_footer %}
  {% javascript 'project-list' %}
{% endblock %}